Product:
  Product_1:
    User: User_4
    Category: Category_18
    name: ASAs
    short_description: sadsad
    description: sadsadsad
    terms: sadasd
    suplier_price: '222.00'
    discount: '22'
    money_save: '48.84'
    price: '173.16'
    stock: '250'
    starttime: '2012-01-15 00:00:00'
    endtime: '2012-01-28 00:00:00'
    sold: '226'
    created_at: '2012-01-15 16:54:48'
    updated_at: '2012-01-16 05:43:06'
    slug: asas
