<?php

/**
 * Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tag extends BaseTag
{
    public function setName($name)
    {
        $slug = Doctrine_Inflector::urlize($name);
        $tag = Doctrine::getTable('Tag')->findOneBySlug($slug);
        if ($tag) {
            $this->assignIdentifier($tag->identifier());
        } else {
            $this->_set('name', $name);
        }
    }
}