<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{
    public function setPassword($password)
    {
        return $this->_set('password', md5($password));
    }
    
    public function preInsert($event)
    {
        /*
         * If no parent was set on defaultController::requestMembership
         * Set a random parent
         */
        
        /*if(!$this->parent_id) {
            $parent = UserTable::getInstance()->getRandomUser()->fetchOne(array(), Doctrine::HYDRATE_ARRAY);
            if($parent['id']) {
                $this->parent_id = $parent['id'];
            }
        }*/
    }
    
    public function postInsert($event)
    {
        if($event->getInvoker()->id) {
            $event->getInvoker()->ref_id = strtolower($event->getInvoker()->UserAddress->Country->code).'-'.strtolower($event->getInvoker()->username).'-'.$event->getInvoker()->id;
            $event->getInvoker()->save();
        }
    }
    
    public function getBuyerTransactionsQuery()
    {
        $q = Doctrine_Query::create()
                ->from('Transaction t')
                ->where('t.by_user_id = ?', $this->id)
                ->orderBy('t.created_at DESC');

        return $q;
    }
    
}