<?php

/**
 * BasePageTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tree_id
 * @property integer $tag_id
 * @property Tree $Tree
 * @property Tag $Tag
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePageTags extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('page_tags');
        $this->hasColumn('tree_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tree', array(
             'local' => 'tree_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}