<?php

/**
 * BaseProductPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property string $name
 * @property double $suplier_price
 * @property integer $discount
 * @property double $money_save
 * @property double $price
 * @property date $expire_at
 * @property integer $stock
 * @property integer $sold
 * @property Product $Product
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductPrice extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_price');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('suplier_price', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('discount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('money_save', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('price', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('expire_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('stock', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('sold', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}