<?php

/**
 * BaseWithdrawRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $status
 * @property double $amount
 * @property string $reason
 * @property User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWithdrawRequest extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('withdraw_request');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('amount', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('reason', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));


        $this->index('statusindex', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}