<?php

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property string $continent
 * @property UserAddress $UserAddress
 * @property CompanyAddress $CompanyAddress
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('code', 'string', 2, array(
             'type' => 'string',
             'length' => '2',
             ));
        $this->hasColumn('continent', 'string', 2, array(
             'type' => 'string',
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserAddress', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasOne('CompanyAddress', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $geographical0 = new Doctrine_Template_Geographical();
        $this->actAs($geographical0);
    }
}